# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: 🏗️ Test Build

on:
  pull_request:
    branches: [develop]
    types: [review_requested, ready_for_review]
    paths-ignore:
    - 'docs/**'
    - 'website/**'
    - 'vendor/**'

jobs:
  Windows-latest:

    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
    - name: 🚛 Checkout Code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: 🧵 Install Requirements
      shell: pwsh
      run: |
        ./tools/manage.ps1 create_env

    - name: 🔨 Build
      shell: pwsh
      run: |
        ./tools/manage.ps1 build

  Ubuntu-latest:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
    - name: 🚛 Checkout Code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: 🧵 Install Requirements
      run: |
        ./tools/make.sh create_env

    - name: 🔨 Build
      run: |
        ./tools/make.sh build
